#%RAML 1.0 DataType

type: object
properties:
  IDproduct : integer
  ProductName : string
  ProductBrand : string
  ProductPrice : number
  ProductNutriscore? : string
  ProductDescription : string
  ProductComposition? : string
  ProductTraceability? : string
  ProductWing : string
  ProductAdvice? : string
  IDproductBarcode : string