#%RAML 1.0 NamedExample


IDproduct : 1
ProductName : 'Lait Demi-Ecreme GRANDLAIT'
ProductBrand : 'Candia'
ProductPrice : 7.20
ProductNutriscore : 'A - 78/100'
ProductDescription : "GrandLait demi-écrémé est idéal pour vous accompagner au..."
ProductComposition : 'LAIT demi écrémé'
ProductTraceability : 'null'
ProductWing : 'Frais > Crèmerie > Laits > Lait demi-écrémé'
ProductAdvice : 'Avant ouverture, à conserver dans un endroit frais et sec.'
IDproductBarcode : '123'